### ISSUE TITLE
optimize algorithms

### ISSUE THREAD

**Issue by i-m-foster** [rporta23/censusviz#11]
Decrease run time for larger counties
- Make 1 dot represent 1000 instead of 100 people?
- Potentially different options for more/less detailed?

**Comment by CJParkNW** [comment]
Ask Ben about any other way to optimize the create_dots() other than increasing how much each dot represents (100 --> 1000)

**Comment by i-m-foster** [comment]
not really any other way to optimize create_dots() so closing issue
