### ISSUE TITLE
div III feedback

### ISSUE THREAD

**Issue by mariumtapal** [rporta23/censusviz#47]
1. Passes `install_github`: ✅ 
2. Documentation builds: ✅
3. Passes R CMD check: ❌

`0 errors ✓ | 0 warnings ✓ | 1 note x`

note:
```
> checking installed package size ... NOTE
    installed size is  6.1Mb
    sub-directories of 1Mb or more:
      data   4.4Mb
      doc    1.5Mb
```

@beanumber

**Comment by beanumber** [comment]
```
✔  checking examples (20.5s)
   Examples with CPU (user + system) or elapsed time > 5s
                   user system elapsed
   get_data_long 18.288  0.481  19.139
```

**Comment by beanumber** [comment]
- The `boston1.png` and `boston2.png` files are 3.4 MB and 3.6 MB, respectively, so those along throw you over the 5 MB limit for the package. Can you downsample those so they aren't so big? 
- You can use `\dontrun{}` to suppress the evaluation of long examples
- Similarly, you can use the `skip()` functions to skip long tests by default
- The title of your vignette is "censusviz" -- can you think of a more descriptive title?

**Comment by rporta23** [comment]
@beanumber we put the images in the rbuildignore file so they are not contributing to the large package size
